### PR TITLE
Fix for exception handling

### PR DESCRIPTION
**Pull request by Terrabits**
This is a fix in reference to [Issue #4](https://github.com/eugeny-dementev/winston-console-formatter/issues/4)

### CODE REVIEW

**Comment by Terrabits** [comment]
Looking at the CI details... I'm not familiar with the Lab testing framework, but the failed check seems to be unrelated to this package. See issues like [this one on Node v6 compatibility](https://github.com/hapijs/lab/issues/581).

To quote that issue:

> ... please disable leak checking (`--leaks`) and try again.

**Comment by eugeny-dementev** [comment]
Hey. Thank you for contribution. Tests case for issue that current fix solves will be nice.

**Comment by Terrabits** [comment]
Yes, tests are important. I generated some, but ran into some other things along the way. See my latest comment [on the open issue](https://github.com/eugeny-dementev/winston-console-formatter/issues/4) for more details.

Also, any comment on disabling leak checking so that checks will pass as long as unit tests pass? Again, I am not familiar with Lab so I don't know if this is a good idea or not.

**Comment by eugeny-dementev** [comment]
Fixed in `1.0.0-beta.1`

**Pull request closed without merging**
